### ISSUE TITLE
Set to []string converter

### ISSUE THREAD

**Issue by tolitius** [go-edn/edn#10]
What would be a good way to have `go-edn` convert a set `#{:a :b}` to `[]string{"a" "b"}`? I understand that the reverse is tricky, but in this case I just need "`EDN => Go`".

Would it be `edn.AddTagFn` + using some internal parse tools from `go-edn`?

An alternative would be to parse EDN sets to `map[string]bool` and just know I need to convert them "manually" before I each use.

**Comment by hypirion** [comment]
The common way to do this is usually to implement `UnmarshalEDN` on a type wrapper for `[]string`, then use that type instead of others:

```go
package main

import (
	"fmt"

	"gopkg.in/edn.v1"
)

type StringSet []string

func (set *StringSet) UnmarshalEDN(bs []byte) error {
	var trueSet map[string]struct{}
	err := edn.Unmarshal(bs, &trueSet)
	if err != nil {
		return err
	}
	var s StringSet
	for key := range trueSet {
		s = append(s, key)
	}
	*set = s
	return nil
}

func main() {
	var set StringSet
	err := edn.UnmarshalString(`#{"foo" "bar" "baz"}`, &set)
	fmt.Println(err)
	fmt.Println(set, set[0], len(set))
}
```

You can also cast the `StringSet` into `[]string` by doing `[]string(set)`.

**Comment by tolitius** [comment]
```clojure
{:foo #{"a" "b"} ...}
```

parses to:

```golang
type Event struct {
        ....
	foo            []string
        ...
}
```

without doing anything.

I added:

```golang
type StringSet []string

func (set *StringSet) UnmarshalEDN(bs []byte) error
```

to see whether it goes there during unmarshalling: it does not. I suspect since it unmarshals the whole structure and not "just" a set portion.

the main problem I have is with real EDN sets with keywords:

```clojure
{:foo #{:a :b} ...}
```

where I get:

```
edn: cannot unmarshal keyword into Go value of type string
```

that is why I thought "`edn.AddTagFn` + using some internal parse tools from `go-edn`"?

**Comment by tolitius** [comment]
or did you mean I would define a
```golang
func (event *Event) UnmarshalEDN(bs []byte) error
```
* unmarshal it there into a `map[string]bool`
* and then walk over the map and
* mutate the "event" to the one with `[]string` for this field instead?

In this case do I have a duplicate / placeholder `[]sting` field on the `Event`? :

```golang
type Event struct {
        ....
        foo                    map[string]bool
	real_foo            []string
        ...
}
```

which seems.. a strange thing to do, hence I wanted to see if I can just narrow down conversion to a single field / type of a struct.

**Comment by tolitius** [comment]
I do have it working by parsing the whole event with sets being `map[edn.Keyword]bool`, and later when I use these fields them I call:
```go
func Keys(m map[edn.Keyword]bool) (keys []string) {
    for k := range m {
    	keys = append(keys, string(k))
    }
    return keys
}
```
I just feel I am missing something and I can plug this converter in `go-edn`

**Comment by hypirion** [comment]
You have to replace `[]string` with `StringSet` in the actual struct, so in your example

```go
type Event struct {
        ....
	foo            StringSet
        ...
}
```

If that's not sufficent, e.g. you really, really want to use `[]string`, I'd usually make two types and UnmarshalEDN from one into the other like so:

```go
type MyType struct {
	foo            []string
}

type myEdnType struct {
	foo            StringSet
        ...
}

func (mt *MyType) UnmarshalEDN(bs []byte) error {
	var data myEdnType
	err := edn.Unmarshal(bs, &data)
	if err != nil {
		return err
	}
	*mt = MyType {
		foo: []string(data.foo),
		bar: data.bar,
		...
	}
	return nil
}
```

**Comment by tolitius** [comment]
makes sense. I am inserting this set into Cassandra (as a set), and Cassandra expects it to be `[]string`. However I "got it to like" `StringSet` as well.

So combining your approach with a tiny change of `map[edn.Keyword]struct{}` vs `map[string]struct{}`, I can know parse a set of keywords (i.e. `#{:a :b}`) into `StringSet` and insert it as one of the fields in a Cassandra table with:

```go
func (set *StringSet) UnmarshalEDN(bs []byte) error {
    var trueSet map[edn.Keyword]struct{}
    err := edn.Unmarshal(bs, &trueSet)
    if err != nil {
    	return err
    }
    var s StringSet
    for key := range trueSet {
    	s = append(s, string(key))
    }
    *set = s
    return nil
}
```

Thanks for pointing out the "common way" of "overriding" behavior on a type wrapper. I was not sure it was a clean way to do it, but as I am reading more and more Go code on github, it is indeed pretty common.
