### ISSUE TITLE
Use JSON struct tags as fallback for missing EDN tags?

### ISSUE THREAD

**Issue by dnaeon** [go-edn/edn#19]
I have a library which contains some generated code which uses `json` tags only for struct fields, and I'd like to be able to use `edn` to marshal/unmarshal the data types, but unfortunately I need to change each struct field and add `edn` tags in order to have the same tag names as the JSON ones.

Is there a way to use `go-edn` in a way which fallbacks to JSON tags if there is no EDN tag for the struct field?

Thanks!

**Comment by hypirion** [comment]
Hi!

I have added the option to use the JSON tag as a fallback through the function `edn.UseJSONAsFallback`, see [the documentation](https://godoc.org/gopkg.in/edn.v1#UseJSONAsFallback) for more, or just include

```go
func init() {
	edn.UseJSONAsFallback(true)
}
```

in the root of your project. I think that should solve your problem :)

**Comment by dnaeon** [comment]
Thanks a lot for this!
