### ISSUE TITLE
Partial Unmarshalling

### ISSUE THREAD

**Issue by tolitius** [go-edn/edn#8]
Is there a way to partially unmarshall EDN. For example:

```go
var data = `{:name "Hans",
             :born 1970,
             :pets [{:name "Cap'n Jack" :kind "Sparrow"}
                    {:name "Freddy" :kind "Cockatiel"}]}`
```
to leave pets as `EDN` via something like:

```go
type Person struct {
	Name      string
	Birthyear int    `edn:"born"`
	Pets      []byte `edn:"*"`
}
```

This is to later persist `Person` structs to a schema based (i.e. SQL/Cassandra/etc) store, with having an ability to persist `Pets` "as EDN" bytes, so Clojure programs would be able to `edn/read-string` these parts of `Person` after reading them back from a store.

Of course in the real life scenario `Pets` may be a quite nested and complex data structure that just would not need a corresponding schema: would need to be saved "as is" to a store.

**Comment by hypirion** [comment]
I added [RawMessage](https://godoc.org/gopkg.in/edn.v1#RawMessage) just now, the EDN-equivalent of `json.RawMessage`. That's seems to solve what you're looking for, if I interpreted you correctly.

Or are you talking about additional fields in general? I.e. we could imagine not only `:pets`, but other fields we did not know about à priori.

**Comment by tolitius** [comment]
great, this is exactly what I am talking about:

```go
type Person struct {
     Name      string
     Birthyear int `edn:"born"`
     Pets      edn.RawMessage
}
```

unmarshals to (string representation):

```go
{Name:Hans Birthyear:1970 Pets: [{:name "Cap'n Jack" :kind "Sparrow"}
                                 {:name "Freddy" :kind "Cockatiel"}]}}
```

so I can get `Pets:` and simply dump them as `[]byte` to a store.

this can be closed and thank you.
