### ISSUE TITLE
What is the recommended way to init "globalTags"?

### ISSUE THREAD

**Issue by tolitius** [go-edn/edn#9]
What is an idiomatic way to "create" `go-edn` with custom conversion functions (that are added to `globalTags` via `edn.AddTagFn`)?

i.e. does not seem reasonable to call "`edn.AddTagFn("uuid", uuid.FromString)`" every time before unmarshalling the message, hence `edn` needs to be initialized beforehand.

It could be a Go question rather than `go-edn`. I can certainly do my own `init()` function that I will call somewhere in `main()` but that feels leaky.

**Comment by tolitius** [comment]
huh.. (still learning `Go`), I did not realize an `init()` function is called on package initialization: https://golang.org/ref/spec#Package_initialization

I was wondering who calls `edn.init()`.

Would the recommended approach be to register custom converters in an `init()` function in one of the application packages that uses `go-edn`?

**Comment by hypirion** [comment]
Yeah, creating an `init` function is what I do, and that's what I recommend unless your application needs to create different types for the same tag (I haven't heard of anyone that has done that).

**Comment by tolitius** [comment]
makes sense. thank you.
